version: "3.2"
services:
  apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - mydata:/usr/local/apache2/htdocs/

volumes:
  mydata:
    driver: azure_file
    driver_opts:
      share_name: is-project
      storage_account_name: webprj